{{
    config(
        materialized='table'
    )
}}

WITH daily_weather AS(
    SELECT 
    DATE(TIME) AS DAILY_WEATHER,
    WEATHER,
    TEMP,
    PRESSURE,
    HUMIDITY,
    CLOUDS
    FROM {{ source('source_demo', 'weather') }}
    
),

DAILY_WEATHER_AGGREGATE AS(

    SELECT 
        DAILY_WEATHER,
        WEATHER,
       -- COUNT(WEATHER) AS COUNT_WEATHER,
       ROUND(AVG(TEMP),2) AS AVG_TEMP,
       ROUND(AVG(PRESSURE),2) AS AVG_PRESSURE,
       ROUND(AVG(HUMIDITY),2) AS AVG_HUMIDITY,
       ROUND(AVG(CLOUDS),2) AS AVG_CLOUDS,
       --ROW_NUMBER() OVER (PARTITION BY DAILY_WEATHER ORDER BY COUNT(WEATHER) DESC) AS ROW_NUMBER

    FROM DAILY_WEATHER
    GROUP BY DAILY_WEATHER,WEATHER
    QUALIFY ROW_NUMBER() OVER (PARTITION BY DAILY_WEATHER ORDER BY COUNT(WEATHER) DESC) = 1

)

SELECT * FROM DAILY_WEATHER_AGGREGATE d 
--WHERE ROW_NUMBER=1