WITH CTE AS(
    SELECT 
        TO_TIMESTAMP(STARTED_AT) AS STARTED_AT
        ,DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT
        ,HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT
        ,DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAY_STARTED_AT
        ,{{day_type('STARTED_AT')}} AS DAY_TYPE
        ,MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_STARTED_AT
        ,{{season_function('STARTED_AT')}} AS SEASON

    FROM {{ source('source_demo', 'bike') }}
    WHERE STARTED_AT != 'started_at'

)

SELECT * FROM CTE 

